services:
  gateway:
    build: ./gateway/
    container_name: gateway_container
    working_dir: /app
    ports:
      - "5000:5000"
    command: "flask run --host=0.0.0.0"
    depends_on:
      - controller
      - user

  controller:
    build: ./control/
    container_name: controller_container
    working_dir: /app
    ports:
      - "5001:5001"
    volumes:
      - session:/app/instance/
    command: "flask run --host=0.0.0.0"

  user:
    build: ./user/
    container_name: user_container
    working_dir: /app
    ports:
      - "5002:5002"
    volumes:
      - user:/app/instance/
    command: "flask run --host=0.0.0.0"

volumes:
  session:
  user:
